Repository googleapis/python-error-reporting, pull requests merged in 2020-12, with the labels that each got.

#41 chore: update intersphinx links
  docs/conf.py
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: partial

#47 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: clouderrorreporting, cla: yes, samples

#53 chore: Re-generated to pick up changes from self.
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: none

#55 chore: re-order imports in `__init__.py`
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: none

#50 chore: add config / docs for 'pre-commit' support
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  noxfile.py
  samples/snippets/api/noxfile.py
  samples/snippets/fluent_on_compute/noxfile.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: full, context: partial

#56 chore: reorder classes
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: none

#57 fix: remove gRPC send/recv limit; add enums to `types/__init__.py`
  google/cloud/errorreporting_v1beta1/services/error_group_service/transports/__init__.py
  google/cloud/errorreporting_v1beta1/services/error_group_service/transports/grpc.py
  google/cloud/errorreporting_v1beta1/services/error_group_service/transports/grpc_asyncio.py
  google/cloud/errorreporting_v1beta1/services/error_stats_service/transports/__init__.py
  google/cloud/errorreporting_v1beta1/services/error_stats_service/transports/grpc.py
  google/cloud/errorreporting_v1beta1/services/error_stats_service/transports/grpc_asyncio.py
  google/cloud/errorreporting_v1beta1/services/report_errors_service/transports/__init__.py
  google/cloud/errorreporting_v1beta1/services/report_errors_service/transports/grpc.py
  google/cloud/errorreporting_v1beta1/services/report_errors_service/transports/grpc_asyncio.py
  google/cloud/errorreporting_v1beta1/types/__init__.py
  synth.metadata
  tests/unit/gapic/errorreporting_v1beta1/test_error_group_service.py
  tests/unit/gapic/errorreporting_v1beta1/test_error_stats_service.py
  tests/unit/gapic/errorreporting_v1beta1/test_report_errors_service.py
Labels: api: clouderrorreporting, cla: yes, context: partial

#60 chore: update templates
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: partial

#61 chore: reorder classes
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: none
