Repository googleapis/python-error-reporting, pull requests merged in 2021-04, with the labels that each got.

#99 deps: upgrade sphinx
  google/cloud/errorreporting_v1beta1/__init__.py
  noxfile.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: none

#104 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: partial

#108 chore: prevent normalization of semver versioning
  setup.py
Labels: api: clouderrorreporting, cla: yes

#110 chore(revert): revert preventing normalization
  setup.py
Labels: api: clouderrorreporting, cla: yes
