Repository googleapis/python-error-reporting, pull requests merged in 2021-05, with the labels that each got.

#111 chore: Re-generated to pick up changes from self.
  google/cloud/errorreporting_v1beta1/__init__.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: none

#113 chore: Re-generated to pick up changes from synthtool.
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  google/cloud/errorreporting_v1beta1/__init__.py
  renovate.json
  samples/snippets/api/noxfile.py
  samples/snippets/fluent_on_compute/noxfile.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: partial

#109 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: api: clouderrorreporting, cla: yes

#118 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: clouderrorreporting, cla: yes

#124 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: clouderrorreporting, automerge, cla: yes
